### ISSUE TITLE
Broken pipe on std::variant with string

### ISSUE THREAD

**Issue by argothiel** [caolanm/callcatcher#12]
When calling callcatcher on the following cpp file, I'm getting the Broken pipe error:

> #include \<variant>
> #include \<string>
> 
> std::variant<std::string, int> _variantWithString;

Steps to reproduce:
- save the above as test.cpp
- run callcatcher g++ -c -std=c++17 test.cpp

Result:

> callcatcher - detecting compiling:
>         collecting test.o
>  'g++' '-c' '-std=c++17' 'test.cpp' '-o' '/login/myuser/.callcatcher/login/myuser/test.o' '-O0' '-S'
> Traceback (most recent call last):
>   File "/login/myuser/opt/bin/callcatcher", line 13, in <module>
>     callcatcher.compile(args)
>   File "/login/myuser/opt/lib/python3.9/site-packages/callcatcher/__init__.py", line 108, in compile
>     aDefines.collect(filename)
>   File "/login/myuser/opt/lib/python3.9/site-packages/callcatcher/defines.py", line 48, in collect
>     realname = aLookup.lookup(name)
>   File "/login/myuser/opt/lib/python3.9/site-packages/callcatcher/lookup.py", line 51, in lookup
>     self.filtin1.flush()
> BrokenPipeError: [Errno 32] Broken pipe
> Exception ignored in: <function Lookup.__del__ at 0x7f57623d5040>
> Traceback (most recent call last):
>   File "/login/myuser/opt/lib/python3.9/site-packages/callcatcher/lookup.py", line 67, in __del__
>     self.filtin1.close()
> BrokenPipeError: [Errno 32] Broken pipe

Expected result:

> callcatcher - detecting compiling:
>         collecting test.o
>  'g++' '-c' '-std=c++17' 'test.cpp' '-o' '/login/myuser/.callcatcher/login/myuser/test.o' '-O0' '-S'
>         0 methods (0 virtual)

**Comment by argothiel** [comment]
Looks like a bug in c++fil (GNU c++filt version 2.27-34.base.el7):

> echo _ZSt7forwardIOZNSt8__detail9__variant16_Variant_storageILb0EJSsiEE8_M_resetEvEUlOT_E_ES5_RNSt16remove_referenceIS4_E4typeE | c++filt
> Segmentation fault (core dumped)

**Comment by caolanm** [comment]
if c++filt is crashing then I guess there's nothing that can be done from callcatcher
